site_name: All The Notes
site_url: https://DrainBamage9.github.io/AllTheNotes/

theme:
  name: material

  palatte:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Dark Mode

  - scheme: slate
    togge:
      icon: material/weather-sunny
      name: Light Mode

docs_dir: docs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
- awesome-pages
- search

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css


exclude_docs: |
  - .obsidian
  - README.md
  - mkdocs.yml
  - .gitignore
  - .gitattributes
  - LICENSE
  - .venv
  - .github



